//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenHoangLaptop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anh
    {
        public int Ma { get; set; }
        public string UrlAnh { get; set; }
        public string TenAnh { get; set; }
        public int MaSP { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
