//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenHoangLaptop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quyen_LoaiTV
    {
        public int MaLoaiTV { get; set; }
        public string MaQuyen { get; set; }
        public string GhiChu { get; set; }
    
        public virtual LoaiThanhVien LoaiThanhVien { get; set; }
        public virtual Quyen Quyen { get; set; }
    }
}
