//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenHoangLaptop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Security.AccessControl;
    using NguyenHoangLaptop.Resource;

    public partial class ThanhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThanhVien()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
            this.KhachHangs = new HashSet<KhachHang>();
        }

        [Display(Name = "Mã Thành Viên")]
        public int MaThanhVien { get; set; }

        [Display(Name = "Account",ResourceType =typeof(Resource))]
        [StringLength(20, ErrorMessage = "Không được quá 20 kí tự")]
        [Required(ErrorMessageResourceType =typeof(Resource),ErrorMessageResourceName = "AccountRequired")]
        public string TaiKhoan { get; set; }

        [Display(Name = "PassWord",ResourceType =typeof(Resource))]
        [Required(ErrorMessageResourceType=typeof(Resource),ErrorMessageResourceName = "PassWordRequired")]
        public string MatKhau { get; set; }

        [Display(Name = "PassWordAgain",ResourceType =typeof(Resource))]
        [Compare("MatKhau",ErrorMessageResourceType =typeof(Resource),ErrorMessageResourceName = "PassWordAgainRequired")]
        public string NhapLaiMatKhau { get; set; }

        [Display(Name = "Name",ResourceType =typeof(Resource))]
        [Required(ErrorMessageResourceType =typeof(Resource),ErrorMessageResourceName = "NameRequired")]
        public string HoTen { get; set; }

        [Display(Name = "Address",ResourceType =typeof(Resource))]
        [Required(ErrorMessageResourceType =typeof(Resource),ErrorMessageResourceName = "AddressRequired")]
        public string DiaChi { get; set; }

        [Display(Name = "Email", ResourceType = typeof(Resource))]
        [Required(ErrorMessageResourceType = typeof(Resource), ErrorMessageResourceName = "EmailRequired")]
        [RegularExpression(@"^([0-9a-zA-Z]([\+\-_\.][0-9a-zA-Z]+)*)+@(([0-9a-zA-Z][-\w]*[0-9a-zA-Z]*\.)+[a-zA-Z0-9]{2,3})$", ErrorMessageResourceType = typeof(Resource), ErrorMessageResourceName = "EmailInvalid")]
        public string Email { get; set; }

        [Display(Name = "PhoneNumber")]
        [Required(ErrorMessageResourceType =typeof(Resource),ErrorMessageResourceName ="PhoneNumberRequired")]
        public Nullable<int> SoDienThoai { get; set; }
        
        [Display(Name ="SecretQuestion")]
        public string CauHoi { get; set; }

        [Display(Name = "Answer")]
        [Required(ErrorMessageResourceType =typeof(Resource),ErrorMessageResourceName = "AnswerRequired")]
        public string CauTraLoi { get; set; }

        public Nullable<int> MaLoaiTV { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhachHang> KhachHangs { get; set; }
        public virtual LoaiThanhVien LoaiThanhVien { get; set; }
    }
}
